<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LT-LP-062" failures="0" tests="2" name="com.lambdatest.TestNGTodo1" time="0.050" errors="1" timestamp="23 Jul 2024 18:09:19 GMT" skipped="1">
  <testcase classname="com.lambdatest.TestNGTodo1" name="basicTest" time="0.000">
    <skipped/>
  </testcase> <!-- basicTest -->
  <testcase classname="com.lambdatest.TestNGTodo1" name="setup" time="0.050">
    <error message="Error at index 0 in: &quot;LoyMEMP9NWiHaeCpfBaGfu7c3hrjYfiksHEe6lSb3zJtqSGp3Zhub.lambdatest.com&quot;" type="java.net.MalformedURLException">
      <![CDATA[java.net.MalformedURLException: Error at index 0 in: "LoyMEMP9NWiHaeCpfBaGfu7c3hrjYfiksHEe6lSb3zJtqSGp3Zhub.lambdatest.com"
at java.base/java.net.URL.<init>(URL.java:709)
at java.base/java.net.URL.<init>(URL.java:570)
at java.base/java.net.URL.<init>(URL.java:517)
at com.lambdatest.TestNGTodo1.setup(TestNGTodo1.java:48)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.NumberFormatException: Error at index 0 in: "LoyMEMP9NWiHaeCpfBaGfu7c3hrjYfiksHEe6lSb3zJtqSGp3Zhub.lambdatest.com"
at java.base/java.lang.NumberFormatException.forCharSequence(NumberFormatException.java:83)
at java.base/java.lang.Integer.parseInt(Integer.java:746)
at java.base/java.net.URLStreamHandler.parseURL(URLStreamHandler.java:231)
at java.base/java.net.URL.<init>(URL.java:704)
... 17 more
]]>
    </error>
  </testcase> <!-- setup -->
</testsuite> <!-- com.lambdatest.TestNGTodo1 -->
